package com.swach.utils;

/**
 * Created by swachdesh on 08/05/15.
 */
public enum  NewCityEnums {
    tinnevelly("tirunelveli"),
    tranquebar("tharangambadi"),
    trichinopoly("tiruchirapalli"),
    madras("chennai"),
    tanjore("thanjavur"),
    karuvur("karur"),
    tuticorin("thoothukudi"),
    capecomorin("kanyakumari"),
    ootacamund("udagamandalam"),
    conjeevaram("kanchipuram"),
    virudupatti("virudhunagar"),
    potonovo("parangipettai"),
    mayavaram("mayiladuthurai"),
    allygurh("aligarh"),
    cawnpore("kanpur"),
    banaras("varanasi"),
    prayag("allahabad"),
    muzaffarnagar("lakshminagar"),
    calcutta("kolkata"),
    burdwan("bardhaman"),
    chinsurah("hugli-chuchura"),
    nowgong("nagaon"),
    gauhati("guwahati"),
    sibsagar("sivasagar"),
    garthapuri("guntur"),
    kandenavolu("kurnool"),
    ellore("eluru"),
    vizagapatam("visakhapatnam"),
    bezawada("vijayawada"),
    cuddapah("ysr district"),
    kadapa("ysr district"),
    cocanada("kakinada"),
    masulipatam("machilipatnam"),
    sikkolu("srikakulam"),
    rajamahendravaramu("rajahmundry"),
    baroda("vadodara"),
    broach("bharuch"),
    cambay("khambhat"),
    bulsar("valsad"),
    simla("shimla"),
    bangalore("bengaluru"),
    mysore("mysuru"),
    mangalore("mangaluru"),
    hubli("hubballi"),
    tumkur("tumakuru"),
    shimoga("shivamogga"),
    belgaum("belagavi"),
    bellary("ballari"),
    gulbarga("kalaburagi"),
    marcera("madikeri"),
    bijapur("vijayapura"),
    hospet("hosapete"),
    chikmagalur("chikkamagaluru"),
    trivandrum("thiruvananthapuram"),
    cochin("kochi"),
    calicut("kozhikode"),
    quilon("kollam"),
    trichur("thrissur"),
    cannanore("kannur"),
    palghat("palakkad"),
    alleppey("alappuzha"),
    alwaye("aluva"),
    parur("north paravur"),
    cranganore("kodungallur"),
    tellicherry("thalassery"),
    badagara("vatakara"),
    palai("pala"),
    verapoly("varapuzha"),
    cherpalchery("cherpulassery"),
    koney("konni"),
    sherthalai("cherthala"),
    indur("indore"),
    avantika("ujjain"),
    bhelsa("vidisha"),
    rassen("raisen"),
    saugor("sagar"),
    jubbulpore("jabalpur"),
    bellasgate("bheraghat"),
    ojjain("ujjaini"),
    mandu("mandavgarh"),
    viratnagari("shahdol"),
    bombay("mumbai"),
    nasik("nashik"),
    poona("pune"),
    thana("thane"),
    bhir("beed"),
    jullunder("jalandhar"),
    ropar("rupnagar"),
    mohali("sas nagar"),
    ajaymeru("ajmer");


    private String newNames;
    private NewCityEnums(String newNames){
        this.newNames=newNames;

    }
    public String getNewNames() {

        return this.newNames;

    }
}
